version: "3.1"

services:

    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: docker-symfony4-mysql
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
        ports:
          - "3036:3036"

    webserver:
      image: nginx
      container_name: docker-symfony4-webserver
      working_dir: /app
      volumes:
          - ./app:/app
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"


    php-fpm:
      build: ./docker/php-fpm
      container_name: docker-symfony4-php-fpm
      working_dir: /app
      volumes:
        - ./app:/app
    
    phpmyadmin:
        links:
          - db
        image: phpmyadmin/phpmyadmin:latest
        container_name: docker-symfony4-phpmyadmin
        restart: always
        ports:
          - '8888:80'
        environment:
          - MYSQL_USER=root
          - MYSQL_PASSWORD=admin
          
